name: 'Go Code Analysis'
description: 'GitHub actions for checking go code'

runs:
  using: "composite"
  steps:
    - name: Install Dependecies
      shell: bash
      run: |
        # Install Go Import Formatter
        go install golang.org/x/tools/cmd/goimports@latest
        # Install Go Security
        curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.14.0
        # Install Go Linter
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0
        # Install Test Coverage Tools
        go install github.com/axw/gocov/gocov@latest
        go install github.com/matm/gocov-html/cmd/gocov-html@latest

    - name: Run Format
      shell: bash
      run: go fmt ./...

    - name: Run Go Import Formatter
      shell: bash
      run: goimports -w $(find . -type f -name '*.go')

    - name: Run Go Vet
      shell: bash
      run: go vet ./...

    - name: Run Go Security
      shell: bash
      run: gosec ./...

    - name: Run Go Lint
      shell: bash
      run: golangci-lint run

    - name: Run Unit Tests
      shell: bash
      run: go test ./...

    - name: Test Coverage
      shell: bash
      run: |
        go test -coverprofile=coverage.xml ./...
        gocov convert coverage.xml | gocov-html > coverage.html

    - name: Upload Coverage
      uses: actions/upload-artifact@v3.1.2
      with:
        name: coverage-html-report
        path: coverage.html